name: lua/luarocks msi creator

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v4
          
      - name: Disable Out of Process Building
        run: .\DisableOutOfProcBuild.exe
        working-directory: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Bootstrap the dependencies
        shell: bash
        run: |
          choco install wget -y
          echo "setting up the dependencies..."
          mkdir tools
          mkdir llvm-mingw-20240502-msvcrt-x86_64
          mkdir lua_deps
          mkdir lua_deps/include
          mkdir lua_deps/lib
          mkdir lua_deps/bin
          mkdir luarocks
          mkdir luarocks/bin
          wget https://raw.githubusercontent.com/justdie386/theinstaller/main/config.lua
          wget https://sourceforge.net/projects/luabinaries/files/5.1.5/Tools%20Executables/lua-5.1.5_Win64_bin.zip/download -O lua_bin.zip
          wget https://sourceforge.net/projects/luabinaries/files/5.1.5/Windows%20Libraries/Dynamic/lua-5.1.5_Win64_dll17_lib.zip/download -O lua_utils.zip
          wget https://luarocks.org/releases/luarocks-3.11.0-windows-64.zip -O luarocks.zip
          wget https://github.com/mstorsjo/llvm-mingw/releases/download/20240502/llvm-mingw-20240502-msvcrt-x86_64.zip -O llvm-mingw.zip
          wget https://gnuwin32.sourceforge.net/downlinks/make-bin-zip.php -O make-bin.zip
          wget https://gnuwin32.sourceforge.net/downlinks/make-dep-zip.php -O make-dep.zip
          wget https://github.com/Kitware/CMake/releases/download/v3.29.3/cmake-3.29.3-windows-x86_64.zip -O cmake.zip
          unzip lua_bin -d lua_deps/bin
          unzip lua_bin 'lua51.dll' -d lua_deps/lib
          unzip lua_utils 'lua5.1.dll' -d lua_deps/lib
          unzip luarocks
          mv luarocks-3.11.0-windows-64/* luarocks/bin
          unzip lua_utils 'include/lualib.h' -d lua_deps
          unzip lua_utils 'include/luaconf.h' -d lua_deps
          unzip lua_utils 'include/lua.hpp' -d lua_deps
          unzip lua_utils 'include/lauxlib.h' -d lua_deps
          unzip lua_utils 'include/lua.h' -d lua_deps
          unzip cmake
          mv cmake-3.29.3-windows-x86_64/* tools
          unzip make-bin -d tools
          unzip make-dep -d tools
          unzip llvm-mingw
          touch tools/README.txt #no idea why its needed
          mv config.lua luarocks/bin
          echo "cleaning up..."
          rm -rf lua_bin.zip
          rm -rf lua_inc.zip
          rm -rf make-bin.zip
          rm -rf make-dep.zip
          rm -rf cmake.zip
          rm -rf cmake-3.29.3-windows-x86_64
          rm -rf llvm-mingw.zip
          rm -rf luarocks.zip
          rm -rf lua-utils.zip
          echo "building editenv"
          cd editenv
          xmake f --toolchain=msvc
          xmake
          cd ..
          echo "letting the system breath, might be causing issues"
          
      - name: upload lua.msi
        run: DevEnv lua/lua.vdproj /build Release
      - uses : actions/upload-artifact@v4
        with: 
          name: lua.msi
          path: lua\Release\
            
